export const API = {
  stocks: {
    list:      '/stocks',
    detail:    (ticker: string) => `/stocks/${ticker}`,
    price:     (ticker: string) => `/stocks/${ticker}/price`,
    disclosures: (ticker: string) => `/stocks/${ticker}/disclosures`,
    news:        (ticker: string) => `/stocks/${ticker}/news`,
    creditBalance: (ticker: string) => `/stocks/${ticker}/credit-balance`,
    valuationBands: (ticker: string) => `/stocks/${ticker}/valuation-bands`,
    compare: '/stocks/compare',
  },
  screener: {
    search:    '/screener',
    presets:   '/screener/presets',
    preset:    (id: string) => `/screener/presets/${id}`,
    sectors:   '/screener/sectors',
  },
  scoring: {
    top:       '/scoring',
    detail:    (ticker: string) => `/scoring/${ticker}`,
  },
  market: {
    indices:   '/market',
    regime:    '/market/regime',
    sectorStocks: (sector: string) => `/market/sectors/${encodeURIComponent(sector)}/stocks`,
    sectors:   '/market/sectors',
    flowsRanking: '/market/flows-ranking',
    quotes:    '/market/quotes',
    macro:     '/market/macro',
    movers:    '/market/movers',
    newListings: '/market/new-listings',
    news:      '/market/news',
    globalPeers: '/market/global-peers',
    symbolChart: '/market/symbol-chart',
    turnover:  '/market/turnover',
    rs:        '/market/rs',
    earningsSurprises: '/market/earnings-surprises',
    outlook:   '/market/outlook',
    outlookSectors: '/market/outlook/sectors',
    monthlyGroups: '/market/monthly/groups',
    monthlyStocks: '/market/monthly/stocks',
    monthlyGroup: (axis: string, key: string) =>
      `/market/monthly/groups/${axis}/${encodeURIComponent(key)}`,
  },
  etf: {
    list:      '/etf',
    board:     '/etf/board',
    boardConfig: '/etf/board-config',
    flows:     '/etf/flows',
    snapshot:  '/etf/snapshot',
    phaseTransitions: '/etf/phase-transitions',
    detail:    (ticker: string) => `/etf/${ticker}`,
  },
  themes: {
    list:      '/themes',
    detail:    (no: number) => `/themes/${no}`,
    refresh:   '/themes/refresh',
    rotation:  '/themes/rotation',
    snapshot:  '/themes/snapshot',
  },
  calendar: {
    earnings:  '/calendar/earnings',
  },
  data: {
    refresh:   '/data/refresh',
    status:    '/data/status',
    summary:   '/data/summary',
  },
  signals: {
    latest:      '/signals',
    performance: '/signals/performance',
    disclosures: '/signals/disclosures',
    history:     (type: string) => `/signals/${type}/history`,
  },
  watchlist: {
    list:      '/watchlist',
    item:      (ticker: string) => `/watchlist/${ticker}`,
  },
  algorithms: {
    list:      '/algorithms',
    update:    (id: string) => `/algorithms/${id}`,
  },
  backtest: {
    run:          '/backtest/run',
    historyDates: '/backtest/history-dates',
    strategies:   '/backtest/strategies',
  },
} as const;
